name: gis
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=h7bae524_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py311hee243d0_0
  - blosc=1.21.6=h5499902_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - contourpy=1.3.3=py311h7d85929_4
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hb547adb_0
  - expat=2.7.3=h50f4ffc_4
  - fiona=1.10.1=py311h595b8b0_3
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.61.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - freexl=2.0.0=h3ab3353_2
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.13.0=hf9b8971_0
  - geotiff=1.7.4=hbef4fa4_0
  - giflib=5.2.2=h93a5062_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libarchive=3.7.7=h7c07d2a_0
  - libavif16=1.3.0=hde9513d_3
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=hb4ce287_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgdal-core=3.10.0=h9ccd308_5
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libheif=1.18.2=gpl_he913df3_100
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - libkml=1.3.0=hc33e383_1022
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.54=h132b30e_0
  - librttopo=1.1.0=ha2cf0f4_17
  - libspatialite=5.1.0=hf92fc0a_12
  - libsqlite=3.51.2=h1b79a29_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.5=hbbdcc80_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h925e9cb_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - minizip=4.0.7=h27ee973_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.1=py311had1e860_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.1=hd24854e_1
  - packaging=25.0=py311hca03da5_1
  - pandas=3.0.0=py311h4a068b9_0
  - pcre2=10.44=ha881caa_2
  - pillow=11.3.0=py311h1f9957d_3
  - pip=25.3=pyhc872135_0
  - proj=9.5.1=h1318a7e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyogrio=0.10.0=py311h595b8b0_1
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.1=py311hfe9757e_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - qhull=2020.2=h420ef59_5
  - rasterio=1.4.3=py311h09e72dc_0
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.8.0=np2py311hf1dd2ad_1
  - scipy=1.17.0=py311he9931d0_1
  - setuptools=80.10.1=py311hca03da5_0
  - shapely=2.0.7=py311h50ea49b_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.1=hab6afd1_0
  - svt-av1=4.0.0=h0cb729a_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - unicodedata2=17.0.0=py311h9408147_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=py311hca03da5_0
  - x265=3.5=hbc6ce65_3
  - xerces-c=3.2.5=h92fc2f4_2
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
prefix: /opt/miniconda3/envs/gis
